apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: dev
  labels:
    app: flaskapp 
spec:
  selector:
    app: flaskapp
  type: ClusterIP
  ports:
    - name: flask-5000
      port: 5000
      targetPort: 5000