apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2048
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2048
  template:
    metadata:
      labels:
        app: app2048
    spec:
      containers:
      - name: app2048
        image: yunjin6121/2048-local:1.0.0-1
        ports:
        - containerPort: 80

