pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins-admin
            """
        }
    }
    environment {
        APP_NAME = "towergame-dev"
    }

    stages {
        stage("Checkout from SCM") {
               steps {
                    sh 'pwd'
                    sh 'ls -al'
                    git branch: 'cjh', credentialsId: 'CJH-GITHUB-CREDENTIAL', url: 'https://github.com/ciscocloud03-team5/gitops-integration'
               }
        }

        stage("Update the Deployment Tags") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-towergame/tower_game-master') {
                        sh """
                        pwd
                        ls -al
                        cat deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        cat deployment.yaml
                        """
                    }
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-towergame/tower_game-master') {
                        sh """
                        git config --global user.email "cjhcjh0429@gmail.com"
                        git config --global user.name "icebreakerrr"
                        git add deployment.yaml
                        git commit -m "Updated Tower Game Deployment Manifest"
                        """
                        withCredentials([gitUsernamePassword(credentialsId: 'CJH-GITHUB-CREDENTIAL', gitToolName: 'Default')]) {
                            sh "git push https://github.com/ciscocloud03-team5/gitops-integration cjh"
                        }
                    }
                }
            }
        }
    }
}
